'

  auto_start_osc: True

  bind_address: auto

  bind_port: 9000

  input_smoothing: 0.8

  walk_threshold: 150

  run_threshold: 400

  walk_key: w

  run_key: shift

  endpoints:

  - endpoint: /accelerometer


  '
